export const V2_EVENT_NAMES = {
  monthlyDeposit: "MonthlyDeposit",
  monthlyWithdrawRequested: "MonthlyWithdrawRequested",
  monthlyWithdrawExecuted: "MonthlyWithdrawExecuted",
  monthlyWithdrawCancelled: "MonthlyWithdrawCancelled",
  monthlyYieldInjected: "MonthlyYieldInjected",
  monthlyNAVUpdated: "MonthlyNAVUpdated",
  monthlyConfigUpdated: "MonthlyConfigUpdated",
  fixedIncomePositionOpened: "FixedIncomePositionOpened",
  fixedIncomeYieldClaimed: "FixedIncomeYieldClaimed",
  fixedIncomeRedeemed: "FixedIncomeRedeemed",
  fixedIncomeEarlyExited: "FixedIncomeEarlyExited",
  fixedIncomeTrancheConfigured: "FixedIncomeTrancheConfigured",
  dealCreated: "DealCreated",
  dealInvestment: "DealInvestment",
  dealRaiseClosed: "DealRaiseClosed",
  dealCapitalDeployed: "DealCapitalDeployed",
  dealRevenueDistributed: "DealRevenueDistributed",
  dealYieldClaimed: "DealYieldClaimed",
  marketplaceListingCreated: "MarketplaceListingCreated",
  marketplaceListingFilled: "MarketplaceListingFilled",
  marketplaceListingCancelled: "MarketplaceListingCancelled",
  marketplacePaused: "MarketplacePaused",
  treasuryYieldRouted: "TreasuryYieldRouted",
  treasuryUpdated: "TreasuryUpdated",
} as const;

export const V2_EVENT_SIGNATURES = [
  "MonthlyDeposit(address,uint256,uint256,uint256)",
  "MonthlyWithdrawRequested(address,uint256,uint256,uint256,uint256)",
  "MonthlyWithdrawExecuted(address,uint256,uint256,uint256,uint256,uint256,bool)",
  "MonthlyWithdrawCancelled(address,uint256,uint256)",
  "MonthlyYieldInjected(address,uint256,uint256,uint256)",
  "MonthlyNAVUpdated(address,uint256,uint256)",
  "MonthlyConfigUpdated(address,string,uint256)",
  "FixedIncomePositionOpened(address,uint256,uint256,uint256,uint256,uint256,uint256)",
  "FixedIncomeYieldClaimed(address,uint256,uint256,uint256)",
  "FixedIncomeRedeemed(address,uint256,uint256,uint256)",
  "FixedIncomeEarlyExited(address,uint256,uint256,uint256)",
  "FixedIncomeTrancheConfigured(address,uint256,uint256,bool)",
  "DealCreated(uint256,address,address,string,uint256,uint256,uint256,uint256)",
  "DealInvestment(uint256,address,uint256,uint256,uint256)",
  "DealRaiseClosed(uint256,address,uint256,uint256)",
  "DealCapitalDeployed(uint256,address,uint256)",
  "DealRevenueDistributed(uint256,address,uint256,uint256)",
  "DealYieldClaimed(uint256,address,uint256)",
  "MarketplaceListingCreated(uint256,uint256,address,address,uint256,uint256)",
  "MarketplaceListingFilled(uint256,uint256,address,address,uint256,uint256,uint256)",
  "MarketplaceListingCancelled(uint256,uint256,address,address,uint256)",
  "MarketplacePaused(address,bool)",
  "TreasuryYieldRouted(address,address,uint256,string)",
  "TreasuryUpdated(address,address)",
] as const;
